### ISSUE TITLE
Support `databuilder --version` on CLI 

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#624]
Unless anyone has better suggestions, this could be done in the same way as we current do for `opensafely-cli`.

1. Have a file at `databuilder/VERSION` whose default contents is `not-from-a-package` or `development` or something like that. (Bonus points if there's something approximating a convention we can follow here.)

2. Read that file at runtime and wire it up to the `--version` argument.

   https://github.com/opensafely-core/opensafely-cli/blob/a9efc8119a979a16fef1dd9ce1e470adad1be2c2/opensafely/__init__.py#L10
   ```py
   __version__ = Path(__file__).parent.joinpath("VERSION").read_text().strip()
   ```
   https://github.com/opensafely-core/opensafely-cli/blob/a9efc8119a979a16fef1dd9ce1e470adad1be2c2/opensafely/__init__.py#L21-L23
   ```py
       parser.add_argument(
           "--version", action="version", version=f"opensafely {__version__}"
       )
   ```

3. Have the action which builds the package write the correct version to the file before building.
   https://github.com/opensafely-core/opensafely-cli/blob/a9efc8119a979a16fef1dd9ce1e470adad1be2c2/.github/workflows/build_and_publish.yaml#L44-L46
   ```yaml
    - name: Generate correct value for VERSION file
      run: |
        echo ${{ needs.tag-new-version.outputs.tag }} > opensafely/VERSION
   ```
