### ISSUE TITLE
Review how Data Builder runs with the OpenSAFELY CLI

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#756]
Does it work following #715?

Can we just run Data Builder without a `project.yaml`?

This is necessary to improve the usability of the software for new users. Particularly it's help for testing the tutorial with users who already have the OpenSAFELY CLI installed.

**Comment by StevenMaude** [comment]
I just tested this and it works with a `project.yaml`.

```
version: "3.0"

expectations:
  population_size: 3000

actions:
  extract_minimal_cohort:
    run: databuilder:dev generate-dataset "./1a_minimal_dataset_definition.py" --dummy-tables "example-data/minimal" --output "outputs/1a_test.csv"
    outputs:
      highly_sensitive:
        cohort: outputs/1a_test.csv
```

Issues:

* We might have to reorganise the tutorial dataset definitions, data and outputs so that each set is in its own directory. Alternatively we could leave it as is, and have.
* There's an `expectations` key which is required, even though it's not used.
